### ISSUE TITLE
OpenWeatherAPI isn't accurate AT ALL

### ISSUE THREAD

**Issue by mhorger3** [mhorger3/SEPTA-UI#1]
So after looking back at some of the data stored in the database, I realized that the weather descriptions and data on rainfall amounts are totally wrong. Temperature seems to be right and wind speed is accurate as well. Just the general descriptions of the weather seem to be off.

For example, today was sunny and not a single drop of rain fell, yet in the database I'm seeing the following records

![image](https://user-images.githubusercontent.com/13708822/54237574-aacc5800-44ec-11e9-8ac6-abf4bee3d5f3.png)

**Comment by jzlotek** [comment]
Dark Sky API
